### ISSUE TITLE
fizzbuzz.py 파일에 내용 구현 및 수정

### ISSUE THREAD

**Issue by shayoyou** [team-fb-1004/fb#2]
## Description
fizzbuzz 기능 구현
ignore 내용 제거

## Tasks

- [x] fizzbuzz 기능 구현
- [x] ignore 내용 제거

**Comment by DavidBae1004** [comment]
네. 관련 이슈 부분을 수정하신 부분 확인했습니다. 관련 코드 confirm후에 merg했습니다. 감사합니다. 기여 +1

**Comment by DavidBae1004** [comment]
완료

**Comment by DavidBae1004** [comment]
네. 수정한 코드 잘 확인했습니다. pull요청 주신 것들 commit처리 완료했습니다. 실력 +2.ㅋㅋ
